### ISSUE TITLE
Perfectly working on simulator but not working on device.

### ISSUE THREAD

**Issue by KralMurat** [tonyli508/LinkedinSwift#1]
Hello,
It's working on simulator but not working on device, nothing happens, not an error, not a warning, nothing. It doesn't get in authorizeSuccess closure. Any idea why?
Thanks in advice.

**Comment by tonyli508** [comment]
Do you have Linkedin app installed on your device? If so you need to setup some key/values in Info.plist for LinkedinSDK. Instruction here: https://developer.linkedin.com/docs/ios-sdk, section `Associate your iOS app with your LinkedIn app` and `iOS 9 Compatibility`

**Comment by KralMurat** [comment]
I configured the info.plist. It opens the linkedin app, and turn back to my app but it comes to 

 [LISDKSessionManager createSessionWithAuth:configuration.permissions state:@"GET-ACCESS-TOKEN" showGoToAppStoreDialog:YES successBlock:^(NSString *returnState) {
                // refresh session
                session = [[LISDKSessionManager sharedInstance] session];
                this->lsAccessToken = [[LSLinkedinToken alloc] initWithAccessToken:session.accessToken.accessTokenValue expireDate:session.accessToken.expiration];
                successCallback(this->lsAccessToken);
            } errorBlock:^(NSError *error) {
                // error code 3 means user cancelled, LISDKErrorCode.USER_CANCELLED doesn't work
                if (error.code == 3) {
                    cancelCallback();
                } else {
                    errorCallback(error);
                }
            }];

this block and then it doesnt get in successBlock or errorBlock.

**Comment by tonyli508** [comment]
Do you have this piece of code in your appDelegate:

```Swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        // Linkedin sdk handle redirect
        if LinkedinSwiftHelper.shouldHandleUrl(url) {
            return LinkedinSwiftHelper.application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
        }
        
        return false
    }
```

**Comment by KralMurat** [comment]
No I didnt, and this was the problem :) Thank you my friend, now it works perfectly
