### ISSUE TITLE
Carthage and Swift 3 Support

### ISSUE THREAD

**Issue by s1Moinuddin** [tonyli508/LinkedinSwift#10]
It would be great if you could provide Carthage support. And also releases for swift 2.3 and swift 3. Thanks in advance.

**Comment by tonyli508** [comment]
Just updated to Swift 3 syntax, have a try. Will investigate how to do the Carthage support later.

**Comment by Urvish-modi** [comment]
if linkedin app exist in my device then code just opens app. Does not ask for verification and does not come back.

**Comment by tonyli508** [comment]
did you follow up the linkedin sdk setup in this link? https://developer.linkedin.com/docs/ios-sdk

**Comment by Urvish-modi** [comment]
@tonyli508 yes everything seems done, looks like minor mistake is done. Here is my program:

that works perfectly if linkedin is not installed in my app.
//Initialize
private let linkedinHelper = LinkedinSwiftHelper(configuration: LinkedinSwiftConfiguration(clientId: K.LINKEDIN_KEY, clientSecret: K.LINKEDIN_SECRET, state: "DLKDJF46ikMMZADfdfds", permissions: ["r_basicprofile", "r_emailaddress"], redirectUrl: K.LINKEDIN_REDIRECT_URL))

//Click
linkedinHelper.authorizeSuccess({ (token) in

            PrintHelper.doPrint(data: token)
            //This token is useful for fetching profile info from LinkedIn server

            self.linkedinHelper.requestURL("https://api.linkedin.com/v1/people/~:(id,first-name,last-name,email-address,picture-url,picture-urls::(original),positions,date-of-birth,phone-numbers,location)?format=json", requestType: LinkedinSwiftRequestGet, success: { (response) -> Void in
                
                PrintHelper.doPrint(data:response)
                
                let json = JSON.init(response.jsonObject)
                
                PrintHelper.doPrint(data:json)
                //parse this response which is in the JSON format
                
            }) {(error) -> Void in
                
                PrintHelper.doPrint(data:error.localizedDescription)
                //handle the error
            }


        }, error: { (error) in

            PrintHelper.doPrint(data: error.localizedDescription)
            //show respective error
        }) {
            //show sign in cancelled event
        }


App Delegate

func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
        if LISDKCallbackHandler.shouldHandle(url)
        {
            return LISDKCallbackHandler.application(app, open: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplicationOpenURLOptionsKey.annotation])
        }
        else if LinkedinSwiftHelper.shouldHandle(url) {
            return LinkedinSwiftHelper.application(app, open: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplicationOpenURLOptionsKey.annotation])
        }
        else{
            return FB
        }
}

Plist

<key>CFBundleURLTypes</key>
<array>
<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>ABCD</string>
			</array>
		</dict>
</array>

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>linkedin.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>

**Comment by tonyli508** [comment]
You miss LIAppId in your info.plist, 	<key>LIAppId</key><string>4127213</string>
