### ISSUE TITLE
Not an issue! BUT! Ability to set the LSLinkedinToken?

### ISSUE THREAD

**Issue by miguelrc86** [tonyli508/LinkedinSwift#12]
Hi @tonyli508 !

First, amazing job here, I'm enjoying your library a lot, but I have this little question... I'm storing the LinkedIn token on the keychain because I though I could use it for later to do a profile "refresh" and ask for new data without doing the whole authentication process again, but then I found the LSLinkedinToken is read only... do you think you could tweak it a little bit so we can do some requests with a stored token? Thanks!

**Comment by tonyli508** [comment]
@jstart ask about similar things a while ago, I'm quite busy at the time. Now probably I can put time to think about how to implement this feature. I probably would add functionality to set token yourself, just need to figure out a nice way, possibly inside initialisation.

**Comment by tonyli508** [comment]
Hi @miguelrc86  ,

Check  [1.7.4](https://github.com/tonyli508/LinkedinSwift/releases/tag/1.7.4) out, see if this is what you want.

```ruby
pod 'LinkedinSwift', '~> 1.7.4'
```

**Comment by miguelrc86** [comment]
Hi @tonyli508 , so sorry to be answering this late, I tested this new feature but unfortunately I'm unable to store the `LSLinkedinToken` in the keychain as this object doesn't conform to NSCoding protocol and I don't want to store it on NSUserDefaults as this is a very unsafe place to do this kind on things. Do you see possible to make this class conform to that protocol? Another option would be that the optional parameter `persistedLSToken` would be the token itself, I mean the string instead of the whole object but not sure if that makes sense, thanks for your time!
