### ISSUE TITLE
Not show anything if LinkedIn App doesn't install

### ISSUE THREAD

**Issue by isatria** [tonyli508/LinkedinSwift#13]
I think there is something wrong, but I've been following all of the examples given. and still nothing happens when linkedin app is not installed on the phone. can you help me. Thanks

**Comment by tonyli508** [comment]
I just tried on my phone, it works for me, I guess is about presentation view controller, you can passing in which view controller you want to present in using LinkedinSwiftHelper(configuration: <#T##LinkedinSwiftConfiguration#>, webOAuthPresent: <#T##UIViewController?#>)

**Comment by isatria** [comment]
Thanks for the answer.
Yes, i try to on my phone and your example project is working.
I think so. it's about presentation. i in presenting modal view.  does it problem?

and can you explain me about present webOAuth ? thanks

**Comment by tonyli508** [comment]
Hi @isatria ,

webOAuthPresent it's a parameter in LinkedinSwiftHelper initialisation function, basically just tell the helper which ViewController you want to present WebView to do the LinkedIn login.

In the end call will be like this:
```swift
webOAuthPresent.present(LinkedinWebViewController, animated: true, completion: nil)
```
