### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by adavan2107** [tonyli508/LinkedinSwift#15]
canOpenURL: failed for URL: "linkedin://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)

**Comment by tonyli508** [comment]
You need add "linkedin://" to your url schemes in info.plist.

**Comment by adavan2107** [comment]
please can you give some example where to add linkedin://

**Comment by tonyli508** [comment]
The key called LSApplicationQueriesSchemes, take a look at my Example project, or check on LinkedIn's instruction: https://developer.linkedin.com/docs/ios-sdk

**Comment by adavan2107** [comment]
Thanks its working but if i login to facebook first and then try to enable linkedin login its not working thanks again for your help

**Comment by adavan2107** [comment]
webOAuthPresent: self this line solved my issue i missed this line while reading description thanks a lot you made my day
