### ISSUE TITLE
r_network(connections)

### ISSUE THREAD

**Issue by Rigelnetworks** [tonyli508/LinkedinSwift#17]
Hi,
    I am trying to integrate linkedin in my app. By using cocoapods i installed sdk but it shows me for error regarding LinkedinSwiftHelper that "undentifier linkedSwiftHelper" and Your project is running well (Example project in swift). But another issue that how to get detail about friend lIst(connections). I want show connections in my app and for that I add parameter called "r_network"
e.g.,
let linkedinHelper = LinkedinSwiftHelper(configuration: LinkedinSwiftConfiguration(clientId: "81x1n8a71cm6ww", clientSecret: "I1uwFGB2vAYQRMRs", state: "DLKDJF46ikMMZADfdfds", permissions: ["r_basicprofile", "r_emailaddress","r_network"], redirectUrl: "http://www.xyz.com/"))

but it gives me error when I log in to it shows your application is not authorized for the scope of "r_network" and when i removed r_network it runs fine. And show info of user (basic profile and emailaddress).

**Comment by tonyli508** [comment]
They have locked down the API and restricted the usage to an extremely limited set of access points from two years ago.

I guess you can request that if you need `r_network`, otherwise you are only allow to use 'r_basicprofile, r_emailaddress, rw_company_admin, w_share'.
