### ISSUE TITLE
Question: Can we force OAuth2 login even when the LinkedIn app is installed?

### ISSUE THREAD

**Issue by Dev-iL** [tonyli508/LinkedinSwift#18]
Hello!

As the title says - I'm wondering if there's a simple way to force OAuth2 despite having the LinkedIn app available. The reason I want to do this is because following the official guides resulted in control not coming back to my app after the LinkedIn login was complete (it just stays inside the LI app; with and without this library). However, when the LI app is removed, the OAuth2 fallback flow works flawlessly.

Thank you for this library!

**Comment by joonhocho** [comment]
I also noticed that official SDK doesnt call the callbacks on both success and error.

**Comment by joonhocho** [comment]
@Dev-iL, My temporary solution is to remove all LSApplicationQueriesSchemes from Info.plist so that your app thinks that LinkedIn app is not installed.

**Comment by tonyli508** [comment]
You can override NativeAppInstalledChecker's isLinkedinAppInstalled function, make it always return false, then pass it into LinkedinSwiftHelper.

**Comment by Dev-iL** [comment]
@joonhocho I came  to share my own "solution" (which I found several days after posting the issue), only to realize that it's identical to yours. I arrived at this workaround after trial and error, so I had no idea why/how it worked... Until now :) Thanks for the explanation!

**Comment by vaibhav-varshaaweblabs** [comment]
@tonyli508 How can we set isLinkedInAppInstalled false?

**Comment by tonyli508** [comment]
@vaibhav-varshaaweblabs subclass NativeAppInstalledChecker's override isLinkedInAppInstalled
