### ISSUE TITLE
Bitcode Errors

### ISSUE THREAD

**Issue by cyurtbil** [tonyli508/LinkedinSwift#19]
Hi,

I have set the bitcode to NO at build Settings of my Target build, however it still doesn't silence the bitcode warnings. Should I set bitcode to no on Pods too?

Thanks

**Comment by tonyli508** [comment]
Should be already disable on the pod, in my case anyway. You can try that anyway, and let me know how it goes.

**Comment by tonyli508** [comment]
turn on Bitcode again on 1.7.7, have a try.
