### ISSUE TITLE
Unable to verify access token

### ISSUE THREAD

**Issue by igordeoliveirasa** [tonyli508/LinkedinSwift#21]
I've been receiving this message when I try to use returned accessToken: Unable to verify access token.

Example: 
```Authorization:  Bearer AQWzZEuWqRimH44StPAHoP8ov7xxzt5MSxFmB3UtqI5Z0OS487fdLa4Kycj-crdfdwpPBvhMkZ9xCGbYXibR-BByhF-1d7NgGk2cpy6zz4O1v0KCa31ClkXiPrLJ93kDFmeiPczP19_f7Q21dvgTPbitfQ1sz107yJ2GXRBFcAXYZ```

P.S.: Above is just an access token example, to keep safe.

**Comment by igordeoliveirasa** [comment]
I've discovered that it should be passed at header: x-li-src: msdk
How could I use it?

**Comment by pinoy4** [comment]
Any luck? @igordeoliveirasa

**Comment by tonyli508** [comment]
@igordeoliveirasa you really should use linkedinHelper.requestURL function, that will manage token for you.
