### ISSUE TITLE
LinkedIn Official SDK doesnt call the callbacks

### ISSUE THREAD

**Issue by joonhocho** [tonyli508/LinkedinSwift#22]
Meanwhile, OAuth 2 works flawlessly.

**Comment by joonhocho** [comment]
Also mentioned in https://github.com/tonyli508/LinkedinSwift/issues/18.

**Comment by joonhocho** [comment]
@tonyli508 @Dev-iL, My temporary solution to this is to remove all LSApplicationQueriesSchemes from Info.plist so that your app thinks that LinkedIn app is not installed and fallbacks to OAuth2.

**Comment by tonyli508** [comment]
Have you tried example app?
