### ISSUE TITLE
10 yellow warnings in newest XCODE

### ISSUE THREAD

**Issue by PanMluvci** [tonyli508/LinkedinSwift#25]
For 10 files i have this warning message:
XYZ was built for newer iOS version (8.1) than being linked (8.0)
Can u please fix this issue @tonyli508 ?

**Comment by felix-dumit** [comment]
I am still getting this issue. If I do:
`pod "LinkedinSwift", git: "https://github.com/tonyli508/LinkedinSwift"`
It works so I think a new version needs to be pushed to cocoapods.
