### ISSUE TITLE
Uses browser even though linkedin app is installed

### ISSUE THREAD

**Issue by freework-tech** [tonyli508/LinkedinSwift#26]
Hi,

I have the problem that the browser is used to login into linkedin instead of the app (the app is installed)

I would post more information but I don't know which one

Thanks,
Ben

**Comment by tonyli508** [comment]
you need to setup LSApplicationQueriesSchemes which is detailed in https://developer.linkedin.com/docs/ios-sdk (section: Whitelisting LinkedIn Custom Schemes)
