### ISSUE TITLE
app install doesn't give back token or profile info only when app uninstall works with web

### ISSUE THREAD

**Issue by jacklandau** [tonyli508/LinkedinSwift#28]

**Comment by tonyli508** [comment]
did you see any error in the console?

**Comment by jacklandau** [comment]
when app is installed this is the console output : "2017-08-16 19:00:16.706038+0100 appname[504:191749] appId=*******"
nothing more

**Comment by skyylex** [comment]
I've seen similar behaviour, in my case I had additional delegate method implemented (for Facebook support). 

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool
```

This one is called as a callback from LinkedIn app. The issue here, that `options` parameter doesn't contain any token. However, when I remove this method and proper method is called - everything is good.

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool
```

**Comment by moazkh60** [comment]
@skyylex please explain a bit more which on is the correct function. I am using this one 

`func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool` and facing the issue. I am unable to pass arguments from LinkedInSwiftHelper to this one

`func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool`

**Comment by tonyli508** [comment]
@moazkh60 check out new readme, it's include a bit detail there.

:warning: for iOS 9 and above use this instead:
```swift
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        // Linkedin sdk handle redirect
        if LinkedinSwiftHelper.shouldHandle(url) {
            return LinkedinSwiftHelper.application(app, open: url, sourceApplication: nil, annotation: nil)
        }
        
        return false
    }
```
