### ISSUE TITLE
AFNetworking Problem 

### ISSUE THREAD

**Issue by aitbaali** [tonyli508/LinkedinSwift#3]
Just after installing pod, I've got this error

`'AFNetworking/AFHTTPRequestOperationManager.h'` file not found in `LIALinkedInApplication`

**Comment by tonyli508** [comment]
Thanks for telling me, I just updated the pod and readme. Try pod 'LinkedinSwift', '~> 1.6'

**Comment by aitbaali** [comment]
thanks for your fast reply 

I've made the changes.
Now I've got
`'LinkedinSwift/LinkedinSwift.h'` file not found in My `Bridging Header`

In my App, I work with the latest AFNetworking version, there's a chance to update to that version.

**Comment by tonyli508** [comment]
Just made it support AFNetworking < and > 3.0 versions, try pod 'LinkedinSwift', '~> 1.6.2'

**Comment by aitbaali** [comment]
thanks @tonyli508 for update,
but I still have the same error
'LinkedinSwift/LinkedinSwift.h' file not found in My Bridging Header

**Comment by tonyli508** [comment]
In my bridging header I use `#import "LSHeader.h"`

**Comment by aitbaali** [comment]
Yes, work's now, thanks
we need to download linkedin app. in order to do login :)?

**Comment by tonyli508** [comment]
You don't need to, it only does when you have linkedin app installed, but if you don't have it will use web view.
