### ISSUE TITLE
View not In view hierarchy

### ISSUE THREAD

**Issue by moazkh60** [tonyli508/LinkedinSwift#30]
whenever I try to open the linkedIn signup using` linkedinHelper.authorizeSuccess({ [unowned self] (lsToken) -> Void in })` It doesn't open saying 

> View Not in window hierarchy

**Comment by ionutboanta** [comment]
Same thing happened to me on the new XCode 9, are there any plans to update the code to swift 3.2 or 4?

**Comment by moazkh60** [comment]
If you install the linkedIn app then this error doesn't occur. It only occurs in web view. A temporary solution is to set the root view controller of the app delegate to current view controller and call this function.

**Comment by tonyli508** [comment]
@moazkh60 you probably init LinkedinHelper with a presentViewController which is not in the window hierarchy when presenting the web login view.

**Comment by moazkh60** [comment]
@tonyli508 you are right. Adding a NavigationController for presenting the view controller resolved the issue.

**Comment by SamaritanMachine** [comment]
I am facing this issue, when pressing the Linkedin login button, it says:
> Attempt to present <UINavigationController: 0x105819e00> on <UINavigationController: 0x10580ca00> whose view is not in the window hierarchy!

And this UINavigationController: 0x105819e00 is my splash view's navigation controller. Why I am getting this? Please help. @moazkh60 @tonyli508

**Comment by moazkh60** [comment]
@SamaritanMachine as you are also using two navigation controllers just like me so on the blue screen viewDidLoad add this line

`let appDelegate = (UIApplication.shared.delegate)
        appDelegate?.window??.rootViewController = navigationController`
