### ISSUE TITLE
Crashed at UXAFURLConnectionOperation.m

### ISSUE THREAD

**Issue by moontecholabs** [tonyli508/LinkedinSwift#32]
in our fabric details we found most of crash occure at  line 159 +[UXAFURLConnectionOperation networkRequestThreadEntryPoint:]  in UXAFURLConnectionOperation.m

above class is of Afnetworking but LinkinSwift in turn use Afnetworking

**Comment by moontecholabs** [comment]
# Crashlytics - plaintext stacktrace downloaded by ios10 at Fri, 13 Oct 2017 11:58:03 GMT
# URL: https://www.fabric.io/mtpl/ios/apps/com.crowdedroad.ifaxpro/issues/59809c7bbe077a4dcc71a7c9/sessions/2404cfa9d5fc45fe960c3dd438fb8f8b_ff93030bafb711e7a39e56847afe9799_0_v2
# Organization: MTPL
# Platform: ios
# Application: iFax
# Version: 6.0.16.19
# Bundle Identifier: com.crowdedroad.ifaxpro
# Issue #: 2054
# Issue ID: 59809c7bbe077a4dcc71a7c9
# Session ID: 2404cfa9d5fc45fe960c3dd438fb8f8b_ff93030bafb711e7a39e56847afe9799_0_v2
# Date: 2017-10-13T01:44:00Z
# OS Version: 10.3.3 (14G60)
# Device: iPhone 7 Plus
# RAM Free: 2.7%
# Disk Free: 51.5%

#0. Crashed: com.apple.main-thread
0  iFax iOS                       0x100a26000 (Missing)
1  libcoretls_cfhelpers.dylib     0x1b6c1e840 (Missing)

--

#0. Crashed: com.apple.main-thread
0  iFax iOS                       0x100a26000 (Missing)
1  libcoretls_cfhelpers.dylib     0x1b6c1e840 (Missing)

#1. Thread
0  libsystem_kernel.dylib         0x18faa5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18fb6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18fb6acac start_wqthread + 4

#2. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1914a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1914c2b84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x1975cb830 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x19159f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#3. Thread
0  libsystem_kernel.dylib         0x18faa5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18fb6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18fb6acac start_wqthread + 4

#4. Thread
0  libsystem_kernel.dylib         0x18faa5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18fb6afd0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x18fb6acac start_wqthread + 4

#5. Thread
0  libsystem_kernel.dylib         0x18faa5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18fb6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18fb6acac start_wqthread + 4

#6. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  iFax iOS                       0x10049a060 CLSMachExceptionServer + 4299677792
3  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
4  libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
5  libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#7. com.google.fira.worker
0  libsystem_kernel.dylib         0x18fa894dc fsync + 8
1  libsqlite3.dylib               0x191007fd8 (null) + 58932
2  libsqlite3.dylib               0x191012d4c (null) + 2244
3  libsqlite3.dylib               0x191007894 (null) + 57072
4  libsqlite3.dylib               0x190ff4578 (null) + 21240
5  libsqlite3.dylib               0x190fc3d70 (null) + 3468
6  libsqlite3.dylib               0x190fed5d8 (null) + 59168
7  libsqlite3.dylib               0x190fdf0c8 sqlite3_step + 528
8  libsqlite3.dylib               0x190fab90c sqlite3_exec + 468
9  iFax iOS                       0x1004ed4cc -[FIRASqliteStore endTransaction] + 4300018892
10 iFax iOS                       0x1004ed354 -[FIRASqliteStore performTransaction:] + 4300018516
11 iFax iOS                       0x100509400 -[FIRAMeasurement writeEventOnWorkerQueue:] + 4300133376
12 iFax iOS                       0x100508e30 -[FIRAMeasurement handleEventOnWorkerQueue:] + 4300131888
13 iFax iOS                       0x100519040 __52-[FIRAScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4300197952
14 libdispatch.dylib              0x18f9629e0 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x18f9629a0 _dispatch_client_callout + 16
16 libdispatch.dylib              0x18f970ad4 _dispatch_queue_serial_drain + 928
17 libdispatch.dylib              0x18f9662cc _dispatch_queue_invoke + 884
18 libdispatch.dylib              0x18f972a50 _dispatch_root_queue_drain + 540
19 libdispatch.dylib              0x18f9727d0 _dispatch_worker_thread3 + 124
20 libsystem_pthread.dylib        0x18fb6b100 _pthread_wqthread + 1096
21 libsystem_pthread.dylib        0x18fb6acac start_wqthread + 4

#8. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x191193df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x19159f318 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
8  libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
9  libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#9. GAIThread
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1914a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1914f6704 -[NSRunLoop(NSRunLoop) run] + 88
7  iFax iOS                       0x10047a39c +[GAI threadMain:] + 4299547548
8  Foundation                     0x19159f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#10. Thread
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1914a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1914f6704 -[NSRunLoop(NSRunLoop) run] + 88
7  iFax iOS                       0x1006039a0 +[UXAFURLConnectionOperation networkRequestThreadEntryPoint:] (UXAFURLConnectionOperation.m:159)
8  Foundation                     0x19159f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#11. Thread
0  libsystem_kernel.dylib         0x18faa4e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18fb6c814 _pthread_cond_wait + 640
2  libc++.1.dylib                 0x18f495ac8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x19533af08 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
4  JavaScriptCore                 0x19533ae7c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x19533ad5c std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x19533b00c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
8  libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
9  libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#12. WebThread
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  WebCore                        0x195658d3c RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
7  libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
8  libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

#13. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x18fa87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18fa8709c mach_msg + 72
2  CoreFoundation                 0x190a58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x190a56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x190986da4 CFRunLoopRunSpecific + 424
5  AVFAudio                       0x1aab314f4 GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x1aab57814 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x18fb6d68c _pthread_body + 240
8  libsystem_pthread.dylib        0x18fb6d59c _pthread_body + 282
9  libsystem_pthread.dylib        0x18fb6acb4 thread_start + 4

**Comment by tonyli508** [comment]
@moontecholabs I need bit more info about the crash, UXAFURLConnectionOperation even not exist in AFNetworking, at least in 3.2.0 (seems it's only an older version issue). So please upgrade to 1.7.7 and have a try.

**Comment by moontecholabs** [comment]
Ok, thank you for your positive reply, we will upgrade with v1.7.7
