### ISSUE TITLE
App redirect issue when LinkedIn App is install.

### ISSUE THREAD

**Issue by EMakadiya** [tonyli508/LinkedinSwift#36]
Hi 

Demo is running fine in simulator when device is not installed. 
But when I tired in real device then its not redirect back to my app when LinkedIn app is install in real device.

Please help me.

**Comment by satishbabariya2** [comment]
Same issue here

**Comment by satishbabariya2** [comment]
Error

li4127213://error?state=GET-ACCESS-TOKEN&info=INVALID_APP_ID&domain=LISDKInvalidRequestError&description=Invalid%20Application%20ID

**Comment by tonyli508** [comment]
did you guys do this: [Associate your iOS app with your LinkedIn app](https://developer.linkedin.com/docs/ios-sdk#) ?
