### ISSUE TITLE
Doesn’t return to my app

### ISSUE THREAD

**Issue by SamaritanMachine** [tonyli508/LinkedinSwift#38]
Linkedin app opens and ask for permissions, I press “OK” button but it doesnt return to my app, permission page closes and appears linkedin homepage. In console writes only my appID. This problem occurs after the update Xcode to 9.2. How can I fix this?

**Comment by tonyli508** [comment]
did you check this out? https://developer.linkedin.com/docs/ios-sdk, especially `iOS 9 Compatibility` section

**Comment by moazkh60** [comment]
@tonyli508 please upgrade the code to swift 4 and so the warnings are removed.

**Comment by Melzar** [comment]
@tonyli508 It's not related to compatibility section at all, I have set it up properly and have the same issue like @SamaritanMachine, is this library maintained or dead?

**Comment by Melzar** [comment]
@SamaritanMachine @tonyli508 I've managed to solve this issue, make sure that you've set in your build settings *bitcode support* to NO also open your plist files and check if there are no newlines in your *LIAppId* or in URL types  li<appid>. It should work correctly after that.
