### ISSUE TITLE
How to use NativeAppInstalledChecker

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [tonyli508/LinkedinSwift#39]
The `LinkedinSwiftConfiguration` initializer has a parameter called `nativeAppChecker` but I can't figure out how or what to use it for. The docs or the example project is missing it too.

I need to check if the native app is installed on the device and if not, direct the user to the App Store to install the app.

Is it possible to do that with the `NativeAppInstalledChecker` and this `nativeAppChecker` parameter?

**Comment by tonyli508** [comment]
You can create NativeAppInstalledChecker in your app and call isLinkedinAppInstalled check if app installed

**Comment by Isuru-Nanayakkara** [comment]
This is how I'm currently doing it.

```swift
if LinkedinSwiftHelper.isLinkedinAppInstalled() {
    let linkedinHelper = LinkedinSwiftHelper(configuration: LinkedinSwiftConfiguration(clientId: "815dicnsjdkd", clientSecret: "RUFN354jkoiR", state: "A4RF32ifjskdmckld", permissions: ["r_basicprofile", "r_emailaddress"], redirectUrl: "https://example.com/signin-linkedin"), nativeAppChecker: nil, clients: nil, webOAuthPresent: self, persistedLSToken: nil)
    linkedinHelper.authorizeSuccess({ token in
        print("Successfully authorized via Linkedin")
    }, error: { error in
        print("Failed to authorize via Linkedin: \(error)")
    }) {
        print("User cancelled authorizing via Linkedin")
    }
}
```

So what's the use of the `nativeAppChecker` parameter? How do I use it?

**Comment by tonyli508** [comment]
actually you are correct, you just need to use isLinkedinAppInstalled on helper. don't need to NativeAppInstalledChecker, unless you want other implementation of it.
