### ISSUE TITLE
Fix in authorization

### ISSUE THREAD

**Issue by jfbomber** [tonyli508/LinkedinSwift#4]
I was receiving an error "Domain=LIALinkedInERROR Code=2". After reading this post https://github.com/jeyben/IOSLinkedInAPI/issues/72. I opened up the LIALinkedInAuthorizationViewController and altered line 134 and it seemed to fix the issue.

**Comment by tonyli508** [comment]
The change's already included in, maybe do a pod update? (delete pod cache before that)

**Comment by tonyli508** [comment]
Sorry, seems after I update the IOSLinkedinAPIFix, forgot to push that to cocoapods, now you can do an update now.
