### ISSUE TITLE
LinkedIn sign in not working

### ISSUE THREAD

**Issue by snehageorge** [tonyli508/LinkedinSwift#45]
I had integrated this library through pods to my app, everything was working perfectly. But when I checked yesterday, in the linkedIn app, after entering email & password, a message is shown that an error has occurred. Hence Im not able to login through LinkedIn. Did anyone face a siimilar issue? How can I fix this ?

**Comment by priyaamirtha** [comment]
same problem i am also facing .are you find any solution for this?

**Comment by priyaamirtha** [comment]
any other way to only navigate to safari

**Comment by tonyli508** [comment]
Yeah, The Mobile SDK is not supported at moment, check this link: https://developer.linkedin.com/docs/ios-sdk, I tried couple way to fix this but no luck, I guess for now we have to disable mobile sdk login. I pushed a new version 1.7.9 to only use web login. Check out the readme and example app.

```swift
let linkedinHelper = LinkedinSwiftHelper(configuration: 
    LinkedinSwiftConfiguration(
        clientId: "77tn2ar7gq6lgv", 
        clientSecret: "iqkDGYpWdhf7WKzA", 
        state: "DLKDJF45DIWOERCM", 
        permissions: ["r_basicprofile", "r_emailaddress"]
    ),
    nativeAppChecker: WebLoginOnly()
)
```

**Comment by tonyli508** [comment]
Please let me know if any you guys find out any works around for the mobile sdk.

**Comment by snehageorge** [comment]
I updated my pods to new version 1.7.9 to only use web login, and changed LinkedinSwiftHelper() to the new one as you mentioned. But now I am getting a screen that says

> Bummer, something went wrong. We're having difficulty connecting.

**Comment by tonyli508** [comment]
@snehageorge it seems like your redirectUrl setting in LinkedinSwiftConfiguration is not matching your Linkedin Oauth 2.0 settings. Check https://www.linkedin.com/developers/apps/{your app id}/auth
