### ISSUE TITLE
Use linked v2 API

### ISSUE THREAD

**Issue by jhpassion0621** [tonyli508/LinkedinSwift#46]
HI tony!

I am using your great library now. By the way Linkedin asks to use v2 api from March 1st. Can you update your library to use v2. Thanks

**Comment by tonyli508** [comment]
@jhpassion0621 thank you for using it, just updated to v2 api. Please check out the Sample project.

**Comment by jhpassion0621** [comment]
How can I get public profile url? @tonyli508

**Comment by tonyli508** [comment]
@jhpassion0621 https://api.linkedin.com/v2/me, it's in both readme and sample project

**Comment by felix-dumit** [comment]
Thanks for updating this! Any ETA on when you'll make a new release with cocoapods?
