### ISSUE TITLE
couldn't logout from current session

### ISSUE THREAD

**Issue by vishalpethani** [tonyli508/LinkedinSwift#49]
linkedinHelper.logout() doesn't work. 
Can anyone tell me that how can I logout current user?

I have download the Example project. When I click on the login button, ViewController is present with LinkedIn Login.

After successful login, ViewController is dismissed, pressed the logout button and once again click on the login button.

I got previous user details.

**Comment by tonyli508** [comment]
@vishalpethani there is a misunderstanding of the logout function, the user you logged in in web view will stay in, the logout function will only clear out the session in current app.

If you need to logout in web view, then only way is going to linkedin in web and logout there.
