### ISSUE TITLE
ViewController not presenting when calling authoriseSuccess method

### ISSUE THREAD

**Issue by dougamos** [tonyli508/LinkedinSwift#5]
The ViewController is not presenting when calling authoriseSuccess method from certain places in my app.  This is the error:

> Attempt to present \<UINavigationController: 0x7b144a00\> on \<Sound_Branch.WelcomeViewController: 0x78e1ad50\> whose view is not in the window hierarchy!

I believe there is a problem because it is being called from within a UINavigationController.  Currently there is no option for defining the presentingViewController. Currently your code does the following:

`httpClient = [LIALinkedInHttpClient clientForApplication:application];`

where doing the following fixes the problem:

`httpClient = [LIALinkedInHttpClient clientForApplication:application presentingViewController:viewController];`

If I had experience with Objective C I would propose a pull request, but do not know the best way to get viewController into the LinkedinSwiftHelper class.

**Comment by tonyli508** [comment]
Hi, if seems your rootViewController is not in the window hierarchy, is there any purpose that you remove you rootViewController after certain point. 

I didn't expose presentViewController for a reason, I don't want to force someone using this library to put it into UI layer. 

You can change
```objective-c
 - (instancetype)initWithConfiguration:(LinkedinSwiftConfiguration*)_configuration presentationViewController:(UIViewController*)viewController
httpClient = [LIALinkedInHttpClient clientForApplication:application presentationViewController:viewController];
```
that will expose the presentationViewController.

**Comment by tonyli508** [comment]
Hi, I just pushed a new version, check it out, @dougamos 

pod 'LinkedinSwift', '= 1.6.6'
