### ISSUE TITLE
LinkedIn requestProfile not working, error: Request failed: no longer exists (410) 

### ISSUE THREAD

**Issue by rajubd49** [tonyli508/LinkedinSwift#51]
![Simulator Screen Shot - iPhone Xʀ - 2019-05-28 at 16 43 37](https://user-images.githubusercontent.com/5569213/58473047-78d0a680-8169-11e9-91ad-9a47bb78dbe7.png)

**Comment by nileshiosdev** [comment]
Hello @rajubd49 
Have you got solution for that ?

**Comment by nileshiosdev** [comment]
Hello @tonyli508 
Could you please let me know, How we will get value of **state** ?
`let linkedinHelper = LinkedinSwiftHelper(configuration: LinkedinSwiftConfiguration(clientId: "77tn2ar7gq6lgv", clientSecret: "iqkDGYpWdhf7WKzA", state: "DLKDJF46ikMMZADfdfds", permissions: ["r_basicprofile", "r_emailaddress"], redirectUrl: "https://github.com/tonyli508/LinkedinSwift"), nativeAppChecker: WebLoginOnly())`

**Comment by rajubd49** [comment]
> Hello @rajubd49
> Have you got solution for that ?

No I did not got any solution yet. My problem was on permissions, I've the r_basicprofile permission before. Now it's gone maybe because LinkedIn only gave the r_liteprofile.

**Comment by tonyli508** [comment]
@nileshiosdev state just a random value to identify the each oauth redirect calls.

**Comment by tonyli508** [comment]
@rajubd49 I just updated linkedin profile request url, should be fine now.

**Comment by rajubd49** [comment]
> @rajubd49 I just updated linkedin profile request url, should be fine now.

Thanks a lot man. One question, so we can't fetch "r_basicprofile" anymore right? I need to fetch user company name and job title info. "r_basicprofile" permission used to provide those info, so is there any way we can get company name and job title info?

Sorry if I'm asking a lot.

**Comment by tonyli508** [comment]
You can still request r_basicprofile permission, that permission is application based, one of my test application has the permission. I didn't find official document about how to request that permission for your application. 

See the [list](https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/full-profile?context=linkedin/consumer/context), even `r_fullprofile` still exist, maybe only for corporate companies. Maybe you can write them an email they will grant it, but I don't have that need. Good luck with it.

**Comment by rajubd49** [comment]
Thanks for your quick reply. 

Just to let you know, I had the r_basicprofile permission on one of my test application and one of my production application. But suddenly LinkedIn removed that on 1 week time difference from both application. I have the screenshots too. 

I guess you are right, maybe they reserve that only for corporate companies. We try to reach reach out to LinkedIn but they did not want to give us the permission maybe because we are a small company.

Thanks again. :)
