### ISSUE TITLE
Issue of UIWebView used which is deprecated.

### ISSUE THREAD

**Issue by rohanmali153** [tonyli508/LinkedinSwift#54]
Hello team,

We have integrated login with linkedin in our app and for this we are using LinkedinSwift Library. Previously it was working fine but before some day ago we got a email(Please check attached image) from apple that Web-view used for login in this library is deprecated. So, they are asking to use alternative for the same. It might create issue in future for our app. So, Would please provide us any alternative solution for it?  

Also, May we know when mobile sdk support will be available ? So, We use same instead of web login ?

Please give your suggestion for our above query as soon as possible. It will be very helpful to us. 

![Screenshot 2019-09-27 at 11 46 31 AM](https://user-images.githubusercontent.com/46746215/65746671-0f63a300-e11d-11e9-875b-c646f92c0124.png)

Thanks,
Rohan

**Comment by ithakkarritesh** [comment]
We are also getting the same error - could you please release the new version.

**Comment by tonyli508** [comment]
Please use 1.8.0.
