### ISSUE TITLE
 New apps that use UIWebView are no longer accepted (New apps that use UIWebView as of April 30, 2020)

### ISSUE THREAD

**Issue by sharmashiv** [tonyli508/LinkedinSwift#56]
Hi Team,

Please resolve this issue ASAP, So we can process our apps 

 Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

grep -Rl 'UIWebView’ .
//LIALinkedInApplication.h
./Pods/IOSLinkedInAPIFix/IOSLinkedInAPI/LIALinkedInHttpClient.h
./Pods/IOSLinkedInAPIFix/IOSLinkedInAPI/LIALinkedInAuthorizationViewController.m
./Pods/IOSLinkedInAPIFix/IOSLinkedInAPI/LIALinkedInApplication.h
./Pods/IOSLinkedInAPIFix/IOSLinkedInAPI/LIALinkedInAuthorizationViewController.h
./Pods/IOSLinkedInAPIFix/README.md
./Pods/LinkedinSwift/README.md

**Comment by bbeutler** [comment]
Please solve this

**Comment by tonyli508** [comment]
Please use 1.8.0
