### ISSUE TITLE
Where can we get the state parameter?

### ISSUE THREAD

**Issue by bbeutler** [tonyli508/LinkedinSwift#57]
let linkedinHelper = LinkedinSwiftHelper(configuration: 
    LinkedinSwiftConfiguration(
        clientId: "77tn2ar7gq6lgv", 
        clientSecret: "iqkDGYpWdhf7WKzA", 
        state: "DLKDJF45DIWOERCM", 
        permissions: ["r_basicprofile", "r_emailaddress"]
    )
)

I can get the client Id and client Secret as well as permissions.
But I can't find where is state string.

**Comment by tonyli508** [comment]
State is a random string, just make sure unique for each app.
