### ISSUE TITLE
Requests fail if LinkedIn app is deleted during lifetime of authed app. 

### ISSUE THREAD

**Issue by markst** [tonyli508/LinkedinSwift#6]
Steps to reproduce:
• Open app and auth LinkedIn user (or recover previous session)
• Tap home button & delete the LinkedIn app
• Attempt to make a request such as fetching users profile

**Comment by markst** [comment]
this appears to be due to auth tokens provided by app not being able to use as Rest requests.
(as http request rather than `LISDKAPIHelper`)

```json
{
  "errorCode": 0,
  "message": "Unable to verify access token",
  "requestId": "BO2KJ42VUP",
  "status": 401,
  "timestamp": 1470741695566
}
```

**Comment by tonyli508** [comment]
I just pushed new version 1.6.5, try it out, thanks for pointing this out. [Tag Link](https://github.com/tonyli508/LinkedinSwift/releases/tag/1.6.5)
